name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0

jobs:
  release:
    name: Release - ${{ matrix.platform.target }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
          - platform_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - platform_name: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin


    runs-on: ${{ matrix.platform.os }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master

      - name: Build executable
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: pubky-cli
          target: ${{ matrix.platform.target }}

